[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#002B36"
idle_fg = "#BCC3C3"
info_bg = "#002B36"
info_fg = "#BCC3C3"
good_bg = "#002B36"
good_fg = "#BCC3C3"
warning_bg = "#ffb52a"
warning_fg = "#002B36"
critical_bg = "#FF0000"
critical_fg = "#BCC3C3"
separator = "â”‚"

[icons]
icons = "material-nf"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/focused-window-name -s 50"
interval = 1

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/tailscale-status"
interval = 5
json = true

[[block.click]]
button = "left"
cmd = "~/.config/i3status-rust/scripts/tailscale-switch-menu"
update = true

[[block.click]]
button = "right"
cmd = "tailscale down || tailscale up"
update = true

[[block]]
block = "battery"
device = "BAT0"
format = " $icon $percentage "
full_format = " $icon $percentage "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d %H:%M:%S') "
